name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl -s "https://sasgrowth.azure-api.net/api/flights/available-dates/count?aggregationField=country&serviceClass=business&outDate=2021-11&adults=2&origin=STO" | jq -r '.' > availability11.json
        curl -s "https://sasgrowth.azure-api.net/api/flights/available-dates/count?aggregationField=country&serviceClass=business&outDate=2022-01&adults=2&origin=STO" | jq -r '.' > availability01.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
